In [1]:
import numpy as np
import tensorflow as tf

In [2]:
dataset = tf.data.Dataset.range(10)

for data in dataset:
    print(data.numpy())

0
1
2
3
4
5
6
7
8
9


In [3]:
dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1)

for window in dataset:
    print(f"list(window) = {list(window)}")

list(window) = [<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=4>]
list(window) = [<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=4>, <tf.Tensor: shape=(), dtype=int64, numpy=5>]
list(window) = [<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=4>, <tf.Tensor: shape=(), dtype=int64, numpy=5>, <tf.Tensor: shape=(), dtype=int64, numpy=6>]
list(window) = [<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=4>, <tf.Tensor: shape=(), dtype=int64, numpy=5>, <tf.Tensor: shape=(), dtype=int64, numpy=6>, <tf.Tensor: shape=(), dtype=int64, numpy=7>]
list(window) = [<tf.Tensor: shape=()

In [4]:
for window in dataset:
    for value in window:
        print(value.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [5]:
dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1, drop_remainder=True)
    
for window in dataset:
    for value in window:
        print(value.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [6]:
dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1, drop_remainder=True)\
    .flat_map(lambda window: window.batch(5))

for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [7]:
def split_x_y(window):
    return window[:-1], window[-1:]

dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1, drop_remainder=True)\
    .flat_map(lambda window: window.batch(5))\
    .map(split_x_y)

for x, y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [8]:
dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1, drop_remainder=True)\
    .flat_map(lambda window: window.batch(5))\
    .map(split_x_y)\
    .shuffle(buffer_size=10)

for x, y in dataset:
  print(x.numpy(), y.numpy())

[2 3 4 5] [6]
[3 4 5 6] [7]
[5 6 7 8] [9]
[4 5 6 7] [8]
[1 2 3 4] [5]
[0 1 2 3] [4]


In [9]:
dataset = tf.data.Dataset.range(10)\
    .window(5, shift=1, drop_remainder=True)\
    .flat_map(lambda window: window.batch(5))\
    .map(split_x_y)\
    .shuffle(buffer_size=10)\
    .batch(2).prefetch(1)

for x, y in dataset:
    print("x = \n", x.numpy())
    print("y = \n", y.numpy())

x = 
 [[1 2 3 4]
 [0 1 2 3]]
y = 
 [[5]
 [4]]
x = 
 [[3 4 5 6]
 [2 3 4 5]]
y = 
 [[7]
 [6]]
x = 
 [[4 5 6 7]
 [5 6 7 8]]
y = 
 [[8]
 [9]]
