In [1]:
import os
import tempfile
import tensorflow_hub as hub
from tensorflow import keras

In [2]:
os.environ['TFHUB_MODEL_LOAD_FORMAT'] = 'COMPRESSED'
os.environ['TFHUB_CACHE_DIR'] = './tfhub_modules'

In [3]:
EMBEDDING_LAYER_URL = 'https://tfhub.dev/google/nnlm-en-dim50/2'

In [4]:
embedding_layer = hub.load(EMBEDDING_LAYER_URL)

In [5]:
text_embeddings = embedding_layer([
    "cat is on the mat", 
    "dog is in the fog"
])
text_embeddings

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[ 0.16589954,  0.0254965 ,  0.1574857 ,  0.17688066,  0.02911299,
        -0.03092718,  0.19445257, -0.05709129, -0.08631689, -0.04391516,
         0.13032274,  0.10905275, -0.08515751,  0.01056632, -0.17220995,
        -0.17925954,  0.19556305,  0.0802278 , -0.03247919, -0.49176937,
        -0.07767699, -0.03160921, -0.13952136,  0.05959712,  0.06858718,
         0.22386682, -0.16653948,  0.19412343, -0.05491862,  0.10997339,
        -0.15811177, -0.02576607, -0.07910853, -0.258499  , -0.04206644,
        -0.20052543,  0.1705603 , -0.15314153,  0.0039225 , -0.28694248,
         0.02468278,  0.11069503,  0.03733957,  0.01433943, -0.11048374,
         0.11931834, -0.11552787, -0.11110869,  0.02384969, -0.07074881],
       [ 0.1437864 ,  0.08291595,  0.10897306,  0.04464385, -0.03630389,
        -0.12605834,  0.20263346,  0.12862863, -0.07873426, -0.01195358,
         0.0020956 , -0.03080653, -0.08019945, -0.18797135, -0.11973457,
 

In [6]:
embedding_layer.embeddings

<tf.Variable 'Variable:0' shape=(963812, 50) dtype=float32, numpy=
array([[-0.07078403,  0.2309921 , -0.04001201, ...,  0.006042  ,
         0.01584901, -0.23308909],
       [ 0.13103518,  0.17923635,  0.01063039, ..., -0.29381433,
         0.05539819,  0.05226879],
       [ 0.06475412, -0.12864912, -0.12485643, ..., -0.16776969,
         0.07435564,  0.19124678],
       ...,
       [ 0.4045343 , -0.17706504, -0.13003995, ..., -0.01742322,
         0.02578888,  0.29181632],
       [ 0.4186347 ,  0.0406054 , -0.14481059, ..., -0.05217805,
         0.03594268,  0.21899657],
       [ 0.4463733 ,  0.06268543,  0.02524463, ...,  0.17416938,
        -0.11148718,  0.2714855 ]], dtype=float32)>

In [7]:
# COMPRESSED_URL = 'https://storage.googleapis.com/tfhub-modules/google/nnlm-en-dim50/2.tar.gz'

# keras.utils.get_file(
#     os.path.basename(COMPRESSED_URL),
#     COMPRESSED_URL,
#     cache_dir='./',
#     cache_subdir='',
#     extract=True
# )

# tokens_file_path = './assets/tokens.txt'

In [8]:
# tokens_file_path = os.path.join(tempfile.gettempdir(), 'tfhub_modules', '74a841d6eb84e8d93d913d716fb5440d020cc291', 'assets', 'tokens.txt')

In [9]:
tokens_file_path = './tfhub_modules/74a841d6eb84e8d93d913d716fb5440d020cc291/assets/tokens.txt'

In [10]:
with open(tokens_file_path, 'r') as f:
    tokens = f.readlines()

tokens = list(map(lambda line: line.rstrip('\n'), tokens))

In [11]:
tokens[:10]

['<S>', '</S>', '<UNK>', ',', 'the', '.', 'to', 'and', 'of', 'a']