In [1]:
import tensorflow as tf

In [2]:
num_steps = 5

In [3]:
def print_dataset(dataset):
    for i, data in enumerate(dataset):
        print(i, ":\t", data)

In [4]:
dataset = tf.data.Dataset.from_tensor_slices(tf.range(15))
print_dataset(dataset)

0 :	 tf.Tensor(0, shape=(), dtype=int32)
1 :	 tf.Tensor(1, shape=(), dtype=int32)
2 :	 tf.Tensor(2, shape=(), dtype=int32)
3 :	 tf.Tensor(3, shape=(), dtype=int32)
4 :	 tf.Tensor(4, shape=(), dtype=int32)
5 :	 tf.Tensor(5, shape=(), dtype=int32)
6 :	 tf.Tensor(6, shape=(), dtype=int32)
7 :	 tf.Tensor(7, shape=(), dtype=int32)
8 :	 tf.Tensor(8, shape=(), dtype=int32)
9 :	 tf.Tensor(9, shape=(), dtype=int32)
10 :	 tf.Tensor(10, shape=(), dtype=int32)
11 :	 tf.Tensor(11, shape=(), dtype=int32)
12 :	 tf.Tensor(12, shape=(), dtype=int32)
13 :	 tf.Tensor(13, shape=(), dtype=int32)
14 :	 tf.Tensor(14, shape=(), dtype=int32)


In [5]:
dataset = dataset.window(num_steps, shift=2, drop_remainder=True)
print_dataset(dataset)

0 :	 <_VariantDataset shapes: (), types: tf.int32>
1 :	 <_VariantDataset shapes: (), types: tf.int32>
2 :	 <_VariantDataset shapes: (), types: tf.int32>
3 :	 <_VariantDataset shapes: (), types: tf.int32>
4 :	 <_VariantDataset shapes: (), types: tf.int32>
5 :	 <_VariantDataset shapes: (), types: tf.int32>


In [6]:
dataset = dataset.flat_map(lambda window: window.batch(num_steps))
print_dataset(dataset)

0 :	 tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
1 :	 tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)
2 :	 tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int32)
3 :	 tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)
4 :	 tf.Tensor([ 8  9 10 11 12], shape=(5,), dtype=int32)
5 :	 tf.Tensor([10 11 12 13 14], shape=(5,), dtype=int32)


In [7]:
dataset = dataset.shuffle(10).map(lambda window: (window[:-1], window[1:]))
print_dataset(dataset)

0 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6])>)
1 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8])>)
2 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([6, 7, 8, 9])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  8,  9, 10])>)
3 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 11, 12, 13])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14])>)
4 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 9, 10, 11, 12])>)
5 :	 (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>)


In [8]:
dataset = dataset.batch(3).prefetch(1)
print_dataset(dataset)

0 :	 (<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[10, 11, 12, 13],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11]])>, <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 9, 10, 11, 12]])>)
1 :	 (<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [2, 3, 4, 5]])>, <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])>)
