In [1]:
import tensorflow as tf

In [2]:
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=0, stddev=0.5), name='W')
b = tf.Variable(initial_value=tf.zeros(shape=(4)), name='b')

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run([W, b])

[array([[-0.05780663,  0.35997713, -0.36555132, -0.18563335]],
       dtype=float32), array([0., 0., 0., 0.], dtype=float32)]

In [4]:
sess.run(tf.assign_add(b, [1, 2, 3, 4]))

array([1., 2., 3., 4.], dtype=float32)

In [5]:
sess.run(b)

array([1., 2., 3., 4.], dtype=float32)

In [6]:
saver = tf.train.Saver({'W': W, 'b': b})
saver.save(sess, './save/save.ckpt', global_step=0)

'./save/save.ckpt-0'

In [7]:
sess.run(tf.assign_add(b, [1, 2, 3, 4]))
sess.run(b)

array([2., 4., 6., 8.], dtype=float32)

In [8]:
saver.restore(sess, './save/save.ckpt-0')
sess.run(b)

INFO:tensorflow:Restoring parameters from ./save/save.ckpt-0


array([1., 2., 3., 4.], dtype=float32)