In [1]:
import tensorflow as tf
from tensorflow.data import Dataset

print(tf.__version__)

2.0.0-beta1


In [2]:
dataset = Dataset.range(10)

for val in dataset:
    print(val.numpy(), end=' ')

0 1 2 3 4 5 6 7 8 9 

In [3]:
dataset = Dataset.range(10) \
    .window(5, shift=1)

for window in dataset:
    for val in window:
        print(val.numpy(), end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [4]:
dataset = Dataset.range(10) \
    .window(5, shift=1, drop_remainder=True)

for window in dataset:
    for val in window:
        print(val.numpy(), end=' ')
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [5]:
dataset = Dataset.range(10) \
    .window(5, shift=1, drop_remainder=True) \
    .flat_map(lambda window: window.batch(5))

for batch in dataset:
    print(batch.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [6]:
dataset = Dataset.range(10) \
    .window(5, shift=1, drop_remainder=True) \
    .flat_map(lambda window: window.batch(5)) \
    .map(lambda batch: (batch[:-1], batch[-1:]))

for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [7]:
dataset = Dataset.range(10) \
    .window(5, shift=1, drop_remainder=True) \
    .flat_map(lambda window: window.batch(5)) \
    .map(lambda batch: (batch[:-1], batch[-1:])) \
    .shuffle(buffer_size=10)

for x, y in dataset:
    print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[3 4 5 6] [7]
[1 2 3 4] [5]
[2 3 4 5] [6]
[5 6 7 8] [9]
[4 5 6 7] [8]


In [8]:
dataset = Dataset.range(10) \
    .window(5, shift=1, drop_remainder=True) \
    .flat_map(lambda window: window.batch(5)) \
    .map(lambda batch: (batch[:-1], batch[-1:])) \
    .shuffle(buffer_size=10) \
    .batch(2).prefetch(1)

for x, y in dataset:
    print("x = \n{}\ny = \n{}".format(x, y))

x = 
[[3 4 5 6]
 [2 3 4 5]]
y = 
[[7]
 [6]]
x = 
[[5 6 7 8]
 [4 5 6 7]]
y = 
[[9]
 [8]]
x = 
[[1 2 3 4]
 [0 1 2 3]]
y = 
[[5]
 [4]]
