In [1]:
import tensorflow as tf
from tensorflow.train import BytesList, FloatList, Int64List, Feature, Features, Example

In [2]:
person_example = Example(
    features=Features(
        feature={
            'name': Feature(bytes_list=BytesList(value=[b"Alice"])),
            'id': Feature(int64_list=Int64List(value=[123])),
            'emails': Feature(bytes_list=BytesList(value=[b"a@b.com", b"c@d.com"]))
        }
    )
)

with tf.io.TFRecordWriter("my_contacts.tfrecord") as f:
    f.write(person_example.SerializeToString())

In [3]:
feature_description = {
    'name': tf.io.FixedLenFeature([], tf.string, default_value=""),
    'id': tf.io.FixedLenFeature([], tf.int64, default_value=0),
    'emails': tf.io.VarLenFeature(tf.string),
}

for serialized_example in tf.data.TFRecordDataset(["my_contacts.tfrecord"]):
    parsed_example = tf.io.parse_single_example(serialized_example, feature_description)
    
parsed_example

{'emails': <tensorflow.python.framework.sparse_tensor.SparseTensor at 0x21b20977a08>,
 'id': <tf.Tensor: shape=(), dtype=int64, numpy=123>,
 'name': <tf.Tensor: shape=(), dtype=string, numpy=b'Alice'>}

In [4]:
parsed_example['name']

<tf.Tensor: shape=(), dtype=string, numpy=b'Alice'>

In [5]:
parsed_example['emails']

In [6]:
parsed_example['emails'].values

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a@b.com', b'c@d.com'], dtype=object)>

In [7]:
parsed_example['emails'].values[0]

<tf.Tensor: shape=(), dtype=string, numpy=b'a@b.com'>

In [8]:
tf.sparse.to_dense(parsed_example['emails'], default_value=b"")

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'a@b.com', b'c@d.com'], dtype=object)>