In [1]:
import tensorflow as tf
from tensorflow.train import BytesList

In [2]:
t = tf.constant([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])
s = tf.io.serialize_tensor(t)
s

<tf.Tensor: shape=(), dtype=string, numpy=b'\x08\x01\x12\x08\x12\x02\x08\x03\x12\x02\x08\x02"\x18\x00\x00\x00\x00\x00\x00\x80?\x00\x00\x00@\x00\x00@@\x00\x00\x80@\x00\x00\xa0@'>

In [3]:
tf.io.parse_tensor(s, out_type=tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)>

In [4]:
sparse = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
sparse

In [5]:
tf.sparse.to_dense(sparse, default_value=0)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 0]])>

In [6]:
serialized_sparse = tf.io.serialize_sparse(sparse)
serialized_sparse

<tf.Tensor: shape=(3,), dtype=string, numpy=
array([b'\x08\t\x12\x08\x12\x02\x08\x02\x12\x02\x08\x02" \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00',
       b'\x08\x03\x12\x04\x12\x02\x08\x02"\x08\x01\x00\x00\x00\x02\x00\x00\x00',
       b'\x08\t\x12\x04\x12\x02\x08\x02"\x10\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'],
      dtype=object)>

In [7]:
BytesList(value=serialized_sparse.numpy())

value: "\010\t\022\010\022\002\010\002\022\002\010\002\" \000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000"
value: "\010\003\022\004\022\002\010\002\"\010\001\000\000\000\002\000\000\000"
value: "\010\t\022\004\022\002\010\002\"\020\003\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000"