In [1]:
import numpy as np
import tensorflow as tf

## Constant scalar

In [2]:
tensor_scalar = tf.constant(42)
tensor_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=42>

## Constant matrix

In [3]:
tensor_matrix = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
tensor_matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tensor_matrix.shape

TensorShape([2, 3])

## Indexing

In [5]:
tensor_matrix[1, :]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [6]:
tensor_matrix[:, 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

## newaxis

In [7]:
tensor_matrix[tf.newaxis].shape

TensorShape([1, 2, 3])

In [8]:
tensor_matrix[:, :, tf.newaxis].shape

TensorShape([2, 3, 1])

## Ops

In [9]:
tensor_matrix + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
tf.square(tensor_matrix)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [11]:
tensor_matrix @ tf.transpose(tensor_matrix)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

## Numpy

In [12]:
np_vector = np.array([1, 2, 3])
tf.constant(np_vector)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [13]:
np_vector = np.array([1.0, 2.0, 3.0])
tf.constant(np_vector)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [14]:
tensor_matrix.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [15]:
tf.square(np_vector)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 9.])>

In [16]:
np.square(tensor_matrix)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

## Casting

In [17]:
tf_float_value = tf.constant(2.0)
tf_float_value

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [18]:
tf_int_value = tf.constant(40)
tf_int_value

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [19]:
try:
    tf_float_value + tf_int_value
except tf.errors.InvalidArgumentError as e:
    print(e)

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]


In [20]:
tf_float_value + tf.cast(tf_int_value, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

## Variable

In [21]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [22]:
v.assign(2 * v)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [23]:
v = 2 * v
v # Note v is tf.Tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

In [24]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v[0, 1].assign(42)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 42.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>

In [25]:
try:
    v[0, 1] = 42
except TypeError as e:
    print(e)

'ResourceVariable' object does not support item assignment


## Set

In [26]:
set_1 = tf.constant([[2, 3, 5, 7], [7, 9, 0, 0]])
set_1

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[2, 3, 5, 7],
       [7, 9, 0, 0]])>

In [27]:
set_2 = tf.constant([[4, 5, 6], [9, 10, 0]])
set_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 9, 10,  0]])>

In [28]:
union = tf.sets.union(set_1, set_2)
union

In [29]:
tf.sparse.to_dense(union)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 2,  3,  4,  5,  6,  7],
       [ 0,  7,  9, 10,  0,  0]])>

In [30]:
tf.sparse.to_dense(tf.sets.intersection(set_1, set_2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 0],
       [0, 9]])>