In [1]:
import tensorflow as tf

In [2]:
tf.constant("hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [3]:
tf.constant(b"hello world")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [4]:
hello = tf.constant("你好")
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'\xe4\xbd\xa0\xe5\xa5\xbd'>

In [5]:
tf.strings.length(hello)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [6]:
tf.strings.length(hello, unit='UTF8_CHAR')

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
code = tf.constant([ord(c) for c in "你好"])
code

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20320, 22909])>

In [8]:
encoded = tf.strings.unicode_encode(code, "UTF-8")
encoded

<tf.Tensor: shape=(), dtype=string, numpy=b'\xe4\xbd\xa0\xe5\xa5\xbd'>

In [9]:
decoded = tf.strings.unicode_decode(encoded, "UTF-8")
decoded

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20320, 22909])>

In [10]:
coffee = tf.constant(["Café", "Coffee", "caffè", "咖啡"])
coffee

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'Caf\xc3\xa9', b'Coffee', b'caff\xc3\xa8',
       b'\xe5\x92\x96\xe5\x95\xa1'], dtype=object)>

In [11]:
tf.strings.length(coffee, unit='UTF8_CHAR')

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 2])>

In [12]:
r = tf.strings.unicode_decode(coffee, "UTF-8")
# Note r is tf.RaggedTensor, nested variable-length lists
r 

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232], [21654, 21857]]>

In [13]:
# r[1] is tf.Tensor (single list)
r[1]

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 67, 111, 102, 102, 101, 101])>

In [14]:
# r[1:3] is tf.RaggedTensor (nested variable-length lists)
r[1:3]

<tf.RaggedTensor [[67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232]]>